### PR TITLE
[issue-65] Update connector to support Pravega client API refactor

### PR DESCRIPTION
**Pull request by vijikarthi**
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>

**Change log description**
  * Updated Pravega to latest snapshot version 0.5.0-49.b80b627-SNAPSHOT
  * Updated Pravega sub-module to the commit point of snapshot version
  * Updated shadow gradle plugin version to fix the shade dependency issue
  * Fixed unit/integration tests

**Purpose of the change**
To address the issue https://github.com/pravega/hadoop-connectors/issues/65

**What the code does**
- Updated Pravega artifact and submodule version to latest snapshot
- Addressed the Pravega client API refactoring changes. 
- Fixed unit/integration tests.

**How to verify it**
`./gradlew clean build` should pass

### CODE REVIEW

**Review by kevinhan88 — APPROVED** [review]
LGTM

**Comment by vijikarthi** [comment]
Created a release branch `0.4.0` from `master` and updated connector version to `0.5.0-SNAPSHOT` as part of this PR.

**Comment by vijikarthi** [comment]
@fpj can this PR be merged?

**Review by fpj — APPROVED** [review]
+1, LGTM

**Pull request merged**
