### PR TITLE
[issue-80] Fix TLS security configuration

### PR DESCRIPTION
**Pull request by vijikarthi**
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>

**Change log description**
  * Updated security configurations to sync with Pravega

**Purpose of the change**
To address https://github.com/pravega/hadoop-connectors/issues/80

**What the code does**
Uses security configurations from Pravega based on changes introduced in pravega/pravega#3693. 

**How to verify it**
./gradlew clean build should pass

### CODE REVIEW

**Review by ravisharda — APPROVED** [review]
LGTM. One of the tests has failed in the Travis CI build, which appears to be unrelated to this PR. Nonetheless, it should be resolved before merging this.

**Comment by vijikarthi** [comment]
> LGTM. One of the tests has failed in the Travis CI build, which appears to be unrelated to this PR. Nonetheless, it should be resolved before merging this.

It looks like an intermittent failure. I have restarted the Travis build and it worked.

**Comment by vijikarthi** [comment]
FYI, I want to merge this PR only after all other PRs are merged.

**Comment by vijikarthi** [comment]
Reverted Pravega version from this PR and created a separate PR https://github.com/pravega/hadoop-connectors/pull/85 to address the Pravega version ugrade

**Review by fpj — APPROVED** [review]

**Pull request merged**
